//! Port of the character class helpers and Perl/POSIX group tables from
//! Go's `regexp/syntax` parser.

use super::gofold::{MAX_FOLD, MIN_FOLD, simple_fold};
use super::gosyntax::MAX_RUNE;

/// Go `charGroup`.
#[derive(Clone, Copy)]
pub struct CharGroup {
    pub sign: i32,
    pub class: &'static [i32],
}

// Code generated by make_perl_groups.pl in Go; ported verbatim.

const CODE1: &[i32] = &[
    // \d
    0x30, 0x39,
];

const CODE2: &[i32] = &[
    // \s
    0x9, 0xa, 0xc, 0xd, 0x20, 0x20,
];

const CODE3: &[i32] = &[
    // \w
    0x30, 0x39, 0x41, 0x5a, 0x5f, 0x5f, 0x61, 0x7a,
];

/// Go `perlGroup`, keyed by the two-byte escape (`\d`, `\D`, ...).
pub fn perl_group(name: &[u8]) -> Option<CharGroup> {
    match name {
        br"\d" => Some(CharGroup {
            sign: 1,
            class: CODE1,
        }),
        br"\D" => Some(CharGroup {
            sign: -1,
            class: CODE1,
        }),
        br"\s" => Some(CharGroup {
            sign: 1,
            class: CODE2,
        }),
        br"\S" => Some(CharGroup {
            sign: -1,
            class: CODE2,
        }),
        br"\w" => Some(CharGroup {
            sign: 1,
            class: CODE3,
        }),
        br"\W" => Some(CharGroup {
            sign: -1,
            class: CODE3,
        }),
        _ => None,
    }
}

const CODE4: &[i32] = &[
    // [:alnum:]
    0x30, 0x39, 0x41, 0x5a, 0x61, 0x7a,
];

const CODE5: &[i32] = &[
    // [:alpha:]
    0x41, 0x5a, 0x61, 0x7a,
];

const CODE6: &[i32] = &[
    // [:ascii:]
    0x0, 0x7f,
];

const CODE7: &[i32] = &[
    // [:blank:]
    0x9, 0x9, 0x20, 0x20,
];

const CODE8: &[i32] = &[
    // [:cntrl:]
    0x0, 0x1f, 0x7f, 0x7f,
];

const CODE9: &[i32] = &[
    // [:digit:]
    0x30, 0x39,
];

const CODE10: &[i32] = &[
    // [:graph:]
    0x21, 0x7e,
];

const CODE11: &[i32] = &[
    // [:lower:]
    0x61, 0x7a,
];

const CODE12: &[i32] = &[
    // [:print:]
    0x20, 0x7e,
];

const CODE13: &[i32] = &[
    // [:punct:]
    0x21, 0x2f, 0x3a, 0x40, 0x5b, 0x60, 0x7b, 0x7e,
];

const CODE14: &[i32] = &[
    // [:space:]
    0x9, 0xd, 0x20, 0x20,
];

const CODE15: &[i32] = &[
    // [:upper:]
    0x41, 0x5a,
];

const CODE16: &[i32] = &[
    // [:word:]
    0x30, 0x39, 0x41, 0x5a, 0x5f, 0x5f, 0x61, 0x7a,
];

const CODE17: &[i32] = &[
    // [:xdigit:]
    0x30, 0x39, 0x41, 0x46, 0x61, 0x66,
];

/// Go `posixGroup`, keyed by the full `[:name:]` text.
pub fn posix_group(name: &str) -> Option<CharGroup> {
    let (sign, class): (i32, &'static [i32]) = match name {
        "[:alnum:]" => (1, CODE4),
        "[:^alnum:]" => (-1, CODE4),
        "[:alpha:]" => (1, CODE5),
        "[:^alpha:]" => (-1, CODE5),
        "[:ascii:]" => (1, CODE6),
        "[:^ascii:]" => (-1, CODE6),
        "[:blank:]" => (1, CODE7),
        "[:^blank:]" => (-1, CODE7),
        "[:cntrl:]" => (1, CODE8),
        "[:^cntrl:]" => (-1, CODE8),
        "[:digit:]" => (1, CODE9),
        "[:^digit:]" => (-1, CODE9),
        "[:graph:]" => (1, CODE10),
        "[:^graph:]" => (-1, CODE10),
        "[:lower:]" => (1, CODE11),
        "[:^lower:]" => (-1, CODE11),
        "[:print:]" => (1, CODE12),
        "[:^print:]" => (-1, CODE12),
        "[:punct:]" => (1, CODE13),
        "[:^punct:]" => (-1, CODE13),
        "[:space:]" => (1, CODE14),
        "[:^space:]" => (-1, CODE14),
        "[:upper:]" => (1, CODE15),
        "[:^upper:]" => (-1, CODE15),
        "[:word:]" => (1, CODE16),
        "[:^word:]" => (-1, CODE16),
        "[:xdigit:]" => (1, CODE17),
        "[:^xdigit:]" => (-1, CODE17),
        _ => return None,
    };
    Some(CharGroup { sign, class })
}

/// Sorts the ranges (pairs of elements of `r`), merges them, and eliminates
/// duplicates. Go `cleanClass`.
pub fn clean_class(r: &mut Vec<i32>) {
    // Sort by lo increasing, hi decreasing to break ties.
    let mut pairs: Vec<(i32, i32)> = r.chunks(2).map(|c| (c[0], c[1])).collect();
    pairs.sort_by(|a, b| a.0.cmp(&b.0).then(b.1.cmp(&a.1)));
    r.clear();
    for (lo, hi) in pairs {
        r.push(lo);
        r.push(hi);
    }

    if r.len() < 2 {
        return;
    }

    // Merge abutting, overlapping.
    let mut w = 2usize; // write index
    let mut i = 2usize;
    while i < r.len() {
        let (lo, hi) = (r[i], r[i + 1]);
        if lo <= r[w - 1] + 1 {
            // merge with previous range
            if hi > r[w - 1] {
                r[w - 1] = hi;
            }
            i += 2;
            continue;
        }
        // new disjoint range
        r[w] = lo;
        r[w + 1] = hi;
        w += 2;
        i += 2;
    }

    r.truncate(w);
}

/// Returns the result of appending the literal `x` to the class `r`.
/// Go `appendLiteral`.
pub fn append_literal(r: &mut Vec<i32>, x: i32, fold_case: bool) {
    if fold_case {
        append_folded_range(r, x, x);
    } else {
        append_range(r, x, x);
    }
}

/// Returns the result of appending the range lo-hi to the class `r`.
/// Go `appendRange`.
pub fn append_range(r: &mut Vec<i32>, lo: i32, hi: i32) {
    // Expand last range or next to last range if it overlaps or abuts.
    // Checking two ranges helps when appending case-folded
    // alphabets, so that one range can be expanding A-Z and the
    // other expanding a-z.
    let n = r.len();
    let mut i = 2usize;
    while i <= 4 {
        // twice, using i=2, i=4
        if n >= i {
            let (rlo, rhi) = (r[n - i], r[n - i + 1]);
            if lo <= rhi + 1 && rlo <= hi + 1 {
                if lo < rlo {
                    r[n - i] = lo;
                }
                if hi > rhi {
                    r[n - i + 1] = hi;
                }
                return;
            }
        }
        i += 2;
    }

    r.push(lo);
    r.push(hi);
}

/// Returns the result of appending the range lo-hi and its case
/// folding-equivalent runes to the class `r`. Go `appendFoldedRange`.
pub fn append_folded_range(r: &mut Vec<i32>, mut lo: i32, mut hi: i32) {
    // Optimizations.
    if lo <= MIN_FOLD && hi >= MAX_FOLD {
        // Range is full: folding can't add more.
        append_range(r, lo, hi);
        return;
    }
    if hi < MIN_FOLD || lo > MAX_FOLD {
        // Range is outside folding possibilities.
        append_range(r, lo, hi);
        return;
    }
    if lo < MIN_FOLD {
        // [lo, minFold-1] needs no folding.
        append_range(r, lo, MIN_FOLD - 1);
        lo = MIN_FOLD;
    }
    if hi > MAX_FOLD {
        // [maxFold+1, hi] needs no folding.
        append_range(r, MAX_FOLD + 1, hi);
        hi = MAX_FOLD;
    }

    // Brute force. Depend on appendRange to coalesce ranges on the fly.
    let mut c = lo;
    while c <= hi {
        append_range(r, c, c);
        let mut f = simple_fold(c);
        while f != c {
            append_range(r, f, f);
            f = simple_fold(f);
        }
        c += 1;
    }
}

/// Returns the result of appending the class `x` to the class `r`.
/// It assumes `x` is clean. Go `appendClass`.
pub fn append_class(r: &mut Vec<i32>, x: &[i32]) {
    let mut i = 0;
    while i < x.len() {
        append_range(r, x[i], x[i + 1]);
        i += 2;
    }
}

/// Returns the result of appending the case folding of the class `x` to the
/// class `r`. Go `appendFoldedClass`.
pub fn append_folded_class(r: &mut Vec<i32>, x: &[i32]) {
    let mut i = 0;
    while i < x.len() {
        append_folded_range(r, x[i], x[i + 1]);
        i += 2;
    }
}

/// Returns the result of appending the negation of the class `x` to the
/// class `r`. It assumes `x` is clean. Go `appendNegatedClass`.
pub fn append_negated_class(r: &mut Vec<i32>, x: &[i32]) {
    let mut next_lo = 0i32;
    let mut i = 0;
    while i < x.len() {
        let (lo, hi) = (x[i], x[i + 1]);
        if next_lo < lo {
            append_range(r, next_lo, lo - 1);
        }
        next_lo = hi + 1;
        i += 2;
    }
    if next_lo <= MAX_RUNE {
        append_range(r, next_lo, MAX_RUNE);
    }
}

/// Overwrites `r` and returns `r`'s negation. It assumes the class `r` is
/// already clean. Go `negateClass`.
pub fn negate_class(r: &mut Vec<i32>) {
    let mut next_lo = 0i32; // lo end of next class to add
    let mut w = 0usize; // write index
    let mut i = 0usize;
    while i < r.len() {
        let (lo, hi) = (r[i], r[i + 1]);
        if next_lo < lo {
            r[w] = next_lo;
            r[w + 1] = lo - 1;
            w += 2;
        }
        next_lo = hi + 1;
        i += 2;
    }
    r.truncate(w);
    if next_lo <= MAX_RUNE {
        // It's possible for the negation to have one more
        // range - this one - than the original class, so use append.
        r.push(next_lo);
        r.push(MAX_RUNE);
    }
}
