//! Port of EsLogs `lib/logstorage/bloomfilter.go`.

use std::sync::Mutex;

use xxhash_rust::xxh64::xxh64;

use esl_common::encoding;
use esl_common::slicesutil;

/// The number of different hashes to use for bloom filter.
pub const BLOOM_FILTER_HASHES_COUNT: usize = 6;

/// The number of bits to use per each token.
pub const BLOOM_FILTER_BITS_PER_ITEM: usize = 16;

/// Appends marshaled bloom filter for tokens to dst.
///
/// PORT NOTE: Go appends to `dst []byte` and returns it; the port mutates
/// `dst` in place (same for the other `dst` parameters in this module).
pub fn bloom_filter_marshal_tokens<S: AsRef<[u8]>>(dst: &mut Vec<u8>, tokens: &[S]) {
    let mut bf = get_bloom_filter();
    bf.must_init_tokens(tokens);
    bf.marshal(dst);
    put_bloom_filter(bf);
}

/// Appends marshaled bloom filter for hashes to dst.
pub fn bloom_filter_marshal_hashes(dst: &mut Vec<u8>, hashes: &[u64]) {
    let mut bf = get_bloom_filter();
    bf.must_init_hashes(hashes);
    bf.marshal(dst);
    put_bloom_filter(bf);
}

/// BloomFilter is a bloom filter over token hashes.
#[derive(Debug, Default)]
pub struct BloomFilter {
    /// The bloom filter bits packed into `u64` words.
    pub bits: Vec<u64>,
}

impl BloomFilter {
    /// Resets the bloom filter.
    pub fn reset(&mut self) {
        self.bits.fill(0);
        self.bits.clear();
    }

    /// Appends marshaled bf to dst.
    pub fn marshal(&self, dst: &mut Vec<u8>) {
        let bits = &self.bits;
        for &word in bits {
            encoding::marshal_uint64(dst, word);
        }
    }

    /// Unmarshals bf from src.
    pub fn unmarshal(&mut self, src: &[u8]) -> Result<(), String> {
        if !src.len().is_multiple_of(8) {
            return Err(format!(
                "cannot unmarshal bloomFilter from src with size not multiple by 8; len(src)={}",
                src.len()
            ));
        }
        self.reset();
        let words_count = src.len() / 8;
        slicesutil::set_length(&mut self.bits, words_count);
        let mut src = src;
        for word in self.bits.iter_mut() {
            *word = encoding::unmarshal_uint64(src);
            src = &src[8..];
        }
        Ok(())
    }

    /// Initializes bf with the given tokens.
    pub fn must_init_tokens<S: AsRef<[u8]>>(&mut self, tokens: &[S]) {
        let bits_count = tokens.len() * BLOOM_FILTER_BITS_PER_ITEM;
        let words_count = bits_count.div_ceil(64);
        slicesutil::set_length(&mut self.bits, words_count);
        bloom_filter_add_tokens(&mut self.bits, tokens);
    }

    /// Initializes bf with the given hashes.
    pub fn must_init_hashes(&mut self, hashes: &[u64]) {
        let bits_count = hashes.len() * BLOOM_FILTER_BITS_PER_ITEM;
        let words_count = bits_count.div_ceil(64);
        slicesutil::set_length(&mut self.bits, words_count);
        bloom_filter_add_hashes(&mut self.bits, hashes);
    }

    /// Returns true if bf contains all the given tokens hashes generated by
    /// [`append_tokens_hashes`] or [`append_hashes_hashes`].
    /// Zero-copy variant of [`BloomFilter::contains_all`]: probes the
    /// marshaled big-endian word array directly, so callers holding the raw
    /// on-disk bytes (e.g. an mmap slice) avoid unmarshalling the whole
    /// filter to inspect a handful of words.
    pub fn bytes_contain_all(raw: &[u8], hashes: &[u64]) -> bool {
        if raw.is_empty() {
            return true;
        }
        debug_assert!(raw.len().is_multiple_of(8));
        let max_bits = (raw.len() / 8) as u64 * 64;
        for &h in hashes {
            let idx = h % max_bits;
            let i = (idx / 64) as usize * 8;
            let j = idx % 64;
            let w = u64::from_be_bytes(raw[i..i + 8].try_into().expect("8-byte word"));
            if (w & (1u64 << j)) == 0 {
                // The token is missing
                return false;
            }
        }
        true
    }

    pub fn contains_all(&self, hashes: &[u64]) -> bool {
        let bits = &self.bits;
        if bits.is_empty() {
            return true;
        }
        let max_bits = (bits.len() as u64) * 64;
        for &h in hashes {
            let idx = h % max_bits;
            let i = (idx / 64) as usize;
            let j = idx % 64;
            let mask = 1u64 << j;
            let w = bits[i];
            if (w & mask) == 0 {
                // The token is missing
                return false;
            }
        }
        true
    }
}

/// Adds the given tokens to the bloom filter bits.
pub fn bloom_filter_add_tokens<S: AsRef<[u8]>>(bits: &mut [u64], tokens: &[S]) {
    let hashes_count = tokens.len() * BLOOM_FILTER_HASHES_COUNT;
    let mut a = encoding::get_uint64s(hashes_count);
    a.a.clear();
    append_tokens_hashes(&mut a.a, tokens);
    init_bloom_filter(bits, &a.a);
    encoding::put_uint64s(a);
}

/// Adds the given hashes to the bloom filter bits.
pub fn bloom_filter_add_hashes(bits: &mut [u64], hashes: &[u64]) {
    let hashes_count = hashes.len() * BLOOM_FILTER_HASHES_COUNT;
    let mut a = encoding::get_uint64s(hashes_count);
    a.a.clear();
    append_hashes_hashes(&mut a.a, hashes);
    init_bloom_filter(bits, &a.a);
    encoding::put_uint64s(a);
}

fn init_bloom_filter(bits: &mut [u64], hashes: &[u64]) {
    let max_bits = (bits.len() as u64) * 64;
    for &h in hashes {
        let idx = h % max_bits;
        let i = (idx / 64) as usize;
        let j = idx % 64;
        let mask = 1u64 << j;
        let w = bits[i];
        if (w & mask) == 0 {
            bits[i] = w | mask;
        }
    }
}

/// Appends hashes for the given tokens to dst.
///
/// The appended hashes can be then passed to `BloomFilter::contains_all()`.
///
/// PORT NOTE: Go stores the intermediate `uint64` into a byte buffer through
/// an unsafe pointer, i.e. in native endianness; `to_ne_bytes` replicates
/// that bit-for-bit on the same platform.
pub fn append_tokens_hashes<S: AsRef<[u8]>>(dst: &mut Vec<u64>, tokens: &[S]) {
    let hashes_count = tokens.len() * BLOOM_FILTER_HASHES_COUNT;
    dst.reserve(hashes_count);

    for token in tokens {
        let mut hp = xxh64(token.as_ref(), 0);
        for _ in 0..BLOOM_FILTER_HASHES_COUNT {
            let h = xxh64(&hp.to_ne_bytes(), 0);
            hp = hp.wrapping_add(1);
            dst.push(h);
        }
    }
}

/// Appends hashes for the given hashes to dst.
///
/// The hashes must be generated from tokens by `tokenize_hashes()`.
/// See also [`append_tokens_hashes`].
///
/// The appended hashes can be then passed to `BloomFilter::contains_all()`.
pub fn append_hashes_hashes(dst: &mut Vec<u64>, hashes: &[u64]) {
    let hashes_count = hashes.len() * BLOOM_FILTER_HASHES_COUNT;
    dst.reserve(hashes_count);

    for &h in hashes {
        let mut hp = h;
        for _ in 0..BLOOM_FILTER_HASHES_COUNT {
            let h = xxh64(&hp.to_ne_bytes(), 0);
            hp = hp.wrapping_add(1);
            dst.push(h);
        }
    }
}

/// Returns a bloom filter from the pool.
///
/// PORT NOTE: Go uses `sync.Pool`; the port uses a `Mutex<Vec<BloomFilter>>`
/// pool and hands filters out by value.
pub fn get_bloom_filter() -> BloomFilter {
    BLOOM_FILTER_POOL.lock().unwrap().pop().unwrap_or_default()
}

/// Returns bf to the pool.
pub fn put_bloom_filter(mut bf: BloomFilter) {
    bf.reset();
    BLOOM_FILTER_POOL.lock().unwrap().push(bf);
}

static BLOOM_FILTER_POOL: Mutex<Vec<BloomFilter>> = Mutex::new(Vec::new());

#[cfg(test)]
mod tests {
    use super::*;
    use crate::hash_tokenizer::tokenize_hashes;

    #[test]
    fn test_bloom_filter() {
        fn f(tokens: &[String]) {
            let mut data_tokens = Vec::new();
            bloom_filter_marshal_tokens(&mut data_tokens, tokens);
            let mut hashes = Vec::new();
            tokenize_hashes(&mut hashes, tokens);
            let mut data_hashes = Vec::new();
            bloom_filter_marshal_hashes(&mut data_hashes, &hashes);
            assert_eq!(
                data_tokens, data_hashes,
                "unexpected marshaled bloom filters from hashes\ngot\n{data_hashes:X?}\nwant\n{data_tokens:X?}"
            );

            let mut bf = get_bloom_filter();
            if let Err(err) = bf.unmarshal(&data_tokens) {
                panic!("unexpected error when unmarshaling bloom filter: {err}");
            }
            let mut tokens_hashes = Vec::new();
            append_tokens_hashes(&mut tokens_hashes, tokens);
            assert!(
                bf.contains_all(&tokens_hashes),
                "containsAll must return true for the added tokens"
            );
            put_bloom_filter(bf);
        }
        f(&[]);
        f(&["foo".to_string()]);
        f(&["foo".to_string(), "bar".to_string(), "baz".to_string()]);

        // 10k tokens
        let tokens: Vec<String> = (0..10000).map(|i| format!("token_{i}")).collect();
        f(&tokens);
    }

    #[test]
    fn test_bloom_filter_unmarshal_failure() {
        fn f(data: &[u8]) {
            let mut bf = get_bloom_filter();
            assert!(bf.unmarshal(data).is_err(), "expecting non-nil error");
            put_bloom_filter(bf);
        }
        f(b"a");
        f(b"foo");
    }

    #[test]
    fn test_bloom_filter_unmarshal_garbage() {
        let data = b"01234567";
        let mut bf = BloomFilter::default();
        if let Err(err) = bf.unmarshal(data) {
            panic!("unexpected error: {err}");
        }
    }

    #[test]
    fn test_bloom_filter_false_positive() {
        let tokens: Vec<String> = (0..20000).map(|i| format!("token_{i}")).collect();
        let mut data = Vec::new();
        bloom_filter_marshal_tokens(&mut data, &tokens);
        let mut bf = get_bloom_filter();
        if let Err(err) = bf.unmarshal(&data) {
            panic!("unexpected error when unmarshaling bloom filter: {err}");
        }

        // count the number of false positives on 20K non-existing tokens
        let mut false_positives = 0usize;
        for i in 0..tokens.len() {
            let token = format!("non-existing-token_{i}");
            let mut tokens_hashes = Vec::new();
            append_tokens_hashes(&mut tokens_hashes, &[token]);
            if bf.contains_all(&tokens_hashes) {
                false_positives += 1;
            }
        }
        let p = false_positives as f64 / tokens.len() as f64;
        let max_false_positive = 0.0011;
        assert!(
            p <= max_false_positive,
            "too high false positive rate; got {p:.4}; want {max_false_positive:.4} max"
        );
        put_bloom_filter(bf);
    }

    #[test]
    fn test_bloom_filter_marshal_tokens_vs_hashes() {
        let tokens: Vec<String> = (0..100).map(|i| format!("token_{i}")).collect();

        let mut data_tokens = Vec::new();
        bloom_filter_marshal_tokens(&mut data_tokens, &tokens);

        let mut hashes = Vec::new();
        tokenize_hashes(&mut hashes, &tokens);
        let mut data_hashes = Vec::new();
        bloom_filter_marshal_hashes(&mut data_hashes, &hashes);

        assert_eq!(
            data_tokens, data_hashes,
            "unexpected bloom filter obtained from hashes\ngot\n{data_hashes:X?}\nwant\n{data_tokens:X?}"
        );
    }

    #[test]
    fn test_bloom_filter_marshal_tokens() {
        fn f(tokens: &[&str], result_expected: &[u8]) {
            let mut result = Vec::new();
            bloom_filter_marshal_tokens(&mut result, tokens);
            assert_eq!(
                result, result_expected,
                "unexpected result\ngot\n{result:X?}\nwant\n{result_expected:X?}"
            );
        }

        f(&[], b"");
        f(&["foo"], b"\x00\x00\x00\x82\x40\x18\x00\x04");
        f(&["foo", "bar", "baz"], b"\x00\x00\x81\xA3\x48\x5C\x10\x26");
        f(
            &["foo", "bar", "baz", "foo"],
            b"\x00\x00\x81\xA3\x48\x5C\x10\x26",
        );
    }
}
