//! Port of EsLogs `lib/logstorage/filter_pattern_match.go`.
//!
//! `FilterPatternMatch` filters field entries by the given pattern, which can be
//! generated by the `collapse_nums` pipe.

use esl_common::panicf;

use crate::bitmap::Bitmap;
use crate::block_result::{BlockResult, ColRef};
use crate::block_search::BlockSearch;
use crate::filter::FieldFilter;
use crate::filter_generic::{FilterGeneric, clone_column_header, new_filter_generic};
use crate::filter_phrase::{
    match_encoded_values_dict, to_float64_string, to_ipv4_string, to_timestamp_iso8601_string,
    visit_values,
};
use crate::filter_prefix::{
    to_int64_string, to_uint8_string, to_uint16_string, to_uint32_string, to_uint64_string,
};
use crate::pattern_matcher::PatternMatcher;
use crate::rows::{Field, get_field_value_by_name};
use crate::stream_filter::quote_token_if_needed;
use crate::values_encoder::ValueType;

/// `FilterPatternMatch` filters field entries by the given pattern, which could
/// be generated by the `collapse_nums` pipe.
///
/// PORT NOTE: Go's `filterPatternMatch` precomputes bloom-filter token hashes in
/// `initTokens` from the `patternMatcher`'s `separators` and `pmo` fields, and
/// uses them in `applyToBlockSearchByField` to skip blocks whose bloom filter
/// lacks the pattern's literal tokens. The Rust `pattern_matcher::PatternMatcher`
/// does not expose `separators`/`pmo` (they are private to that module, which is
/// outside this port's editable set), so the bloom-filter token pre-filter is
/// omitted here. This is a pure performance optimization: with no tokens,
/// `match_bloom_filter_all_tokens` would return `true` anyway, so every matching
/// path is preserved and the results are identical to Go.
pub(crate) struct FilterPatternMatch {
    func_name: String,
    pm: PatternMatcher,
}

pub(crate) fn new_filter_pattern_match(
    field_name: &str,
    func_name: &str,
    pm: PatternMatcher,
) -> FilterGeneric {
    new_filter_generic(
        field_name,
        Box::new(FilterPatternMatch {
            func_name: func_name.to_string(),
            pm,
        }),
    )
}

/// Matches the raw value bytes `v` against `pm`.
///
/// PORT NOTE: Go's `patternMatcher.Match` operates on arbitrary bytes, while
/// the port's `PatternMatcher::matches` takes `&str`. Valid UTF-8 values match
/// identically (the matcher is byte-oriented internally); invalid UTF-8 values
/// fall back to matching the lossy-decoded string — a documented residual
/// difference from Go (same class as regex-on-invalid-utf8).
fn match_pattern_bytes(pm: &PatternMatcher, v: &[u8]) -> bool {
    match std::str::from_utf8(v) {
        Ok(s) => pm.matches(s),
        Err(_) => pm.matches(&String::from_utf8_lossy(v)),
    }
}

impl FilterPatternMatch {
    fn match_column_generic(&self, br: &mut BlockResult, bm: &mut Bitmap, r: ColRef) {
        let pm = &self.pm;
        let values = br.column_get_values(r);
        bm.for_each_set_bit(|idx| match_pattern_bytes(pm, &values[idx]));
    }
}

impl FieldFilter for FilterPatternMatch {
    fn to_string(&self) -> String {
        format!(
            "{}({})",
            self.func_name,
            quote_token_if_needed(&self.pm.to_string())
        )
    }

    fn match_row_by_field(&self, fields: &[Field], field_name: &str) -> bool {
        let v = get_field_value_by_name(fields, field_name);
        match_pattern_bytes(&self.pm, v)
    }

    fn apply_to_block_result_by_field(
        &self,
        br: &mut BlockResult,
        bm: &mut Bitmap,
        field_name: &str,
    ) {
        let r = br.get_column_by_name(field_name);
        if br.column_is_const(r) {
            let v = br.column_get_value_at_row(r, 0);
            if !match_pattern_bytes(&self.pm, v) {
                bm.reset_bits();
            }
            return;
        }
        if br.column_is_time(r) {
            self.match_column_generic(br, bm, r);
            return;
        }

        match br.column_value_type(r) {
            // PORT NOTE: Go's `valueTypeDict` case builds a per-dict-entry table
            // from `c.dictValues`. `BlockResult` does not expose `dictValues`, so
            // the port routes the dict case through the already-decoded per-row
            // values (identical result).
            ValueType::STRING
            | ValueType::DICT
            | ValueType::UINT8
            | ValueType::UINT16
            | ValueType::UINT32
            | ValueType::UINT64
            | ValueType::INT64
            | ValueType::FLOAT64
            | ValueType::IPV4
            | ValueType::TIMESTAMP_ISO8601 => {
                self.match_column_generic(br, bm, r);
            }
            other => panicf!("FATAL: unknown valueType={}", other.0),
        }
    }

    fn apply_to_block_search_by_field(
        &self,
        bs: &mut BlockSearch<'_>,
        bm: &mut Bitmap,
        field_name: &str,
    ) {
        // Verify whether fp matches const column.
        let v = bs.get_const_column_value(field_name);
        if !v.is_empty() {
            if !match_pattern_bytes(&self.pm, &v) {
                bm.reset_bits();
            }
            return;
        }

        // Verify whether fp matches other columns.
        let ch = match bs.get_column_header(field_name) {
            Some(ch) => clone_column_header(ch),
            None => {
                // Fast path - there are no matching columns.
                if !self.pm.matches("") {
                    bm.reset_bits();
                }
                return;
            }
        };

        let pm = &self.pm;

        match ch.value_type {
            ValueType::STRING => {
                visit_values(bs, &ch, bm, |v| match_pattern_bytes(pm, v));
            }
            ValueType::DICT => {
                let mut bb = Vec::with_capacity(ch.values_dict.values.len());
                for v in &ch.values_dict.values {
                    bb.push(u8::from(match_pattern_bytes(pm, v)));
                }
                match_encoded_values_dict(bs, &ch, bm, &bb);
            }
            ValueType::UINT8 => {
                let pp = bs.part_path();
                visit_values(bs, &ch, bm, |v| {
                    let mut bb = Vec::new();
                    to_uint8_string(&pp, &mut bb, v);
                    match_pattern_bytes(pm, &bb)
                });
            }
            ValueType::UINT16 => {
                let pp = bs.part_path();
                visit_values(bs, &ch, bm, |v| {
                    let mut bb = Vec::new();
                    to_uint16_string(&pp, &mut bb, v);
                    match_pattern_bytes(pm, &bb)
                });
            }
            ValueType::UINT32 => {
                let pp = bs.part_path();
                visit_values(bs, &ch, bm, |v| {
                    let mut bb = Vec::new();
                    to_uint32_string(&pp, &mut bb, v);
                    match_pattern_bytes(pm, &bb)
                });
            }
            ValueType::UINT64 => {
                let pp = bs.part_path();
                visit_values(bs, &ch, bm, |v| {
                    let mut bb = Vec::new();
                    to_uint64_string(&pp, &mut bb, v);
                    match_pattern_bytes(pm, &bb)
                });
            }
            ValueType::INT64 => {
                let pp = bs.part_path();
                visit_values(bs, &ch, bm, |v| {
                    let mut bb = Vec::new();
                    to_int64_string(&pp, &mut bb, v);
                    match_pattern_bytes(pm, &bb)
                });
            }
            ValueType::FLOAT64 => {
                let pp = bs.part_path();
                visit_values(bs, &ch, bm, |v| {
                    let mut bb = Vec::new();
                    to_float64_string(&pp, &mut bb, v);
                    match_pattern_bytes(pm, &bb)
                });
            }
            ValueType::IPV4 => {
                let pp = bs.part_path();
                visit_values(bs, &ch, bm, |v| {
                    let mut bb = Vec::new();
                    to_ipv4_string(&pp, &mut bb, v);
                    match_pattern_bytes(pm, &bb)
                });
            }
            ValueType::TIMESTAMP_ISO8601 => {
                let pp = bs.part_path();
                visit_values(bs, &ch, bm, |v| {
                    let mut bb = Vec::new();
                    to_timestamp_iso8601_string(&pp, &mut bb, v);
                    match_pattern_bytes(pm, &bb)
                });
            }
            other => panicf!("FATAL: {}: unknown valueType={}", bs.part_path(), other.0),
        }
    }
}
